<?php

return [
    'resources' => [
        'finance.chart_of_accounts' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/ChartOfAccounts?$select=Code,Name,ActiveAccount,FatherAccountKey,GroupMask&$top=200',
            'key_candidates' => ['Code'],
            'name_candidates' => ['Name'],
        ],
        'finance.account_categories' => [
            'module' => 'finance',
            'mode' => 'raw',
            'path' => '/AccountCategoryService_GetCategoryList',
            'key_candidates' => ['Category', 'CategoryCode', 'GroupCode', 'Code', 'Value'],
            'name_candidates' => ['CategoryName', 'Name', 'Description', 'Value'],
        ],
        'finance.financial_periods' => [
            'module' => 'finance',
            'mode' => 'raw',
            'path' => '/CompanyService_GetPeriods',
            'key_candidates' => ['AbsoluteEntry', 'PeriodCode', 'Code', 'Category', 'StartDate'],
            'name_candidates' => ['PeriodName', 'Name', 'SubPeriodName', 'Category'],
        ],
        'finance.invoices' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/Invoices?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'finance.credit_notes' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/CreditNotes?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'finance.down_payments' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/DownPayments?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'finance.incoming_payments' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/IncomingPayments?$select=DocEntry,DocNum,CardCode,DocDate,TransferSum&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'finance.purchase_invoices' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/PurchaseInvoices?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'finance.purchase_credit_notes' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/PurchaseCreditNotes?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'finance.purchase_down_payments' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/PurchaseDownPayments?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'finance.vendor_payments' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/VendorPayments?$select=DocEntry,DocNum,CardCode,DocDate,TransferSum&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'finance.banks' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/Banks?$select=BankCode,BankName&$top=200',
            'key_candidates' => ['BankCode'],
            'name_candidates' => ['BankName'],
        ],
        'finance.bank_accounts' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/HouseBankAccounts?$select=BankCode,AccountCode,AccountNo,Branch&$top=200',
            'key_candidates' => ['AccountCode', 'AbsEntry', 'AccountNo'],
            'name_candidates' => ['AccountNo', 'AccountCode'],
        ],
        'finance.currencies' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/Currencies?$select=Code,Name&$top=200',
            'key_candidates' => ['Code'],
            'name_candidates' => ['Name'],
        ],
        'finance.exchange_rates' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/CurrencyRates?$select=Currency,RateDate,Rate&$top=200',
            'key_candidates' => ['Currency', 'CurrencyCode', 'RateDate'],
            'name_candidates' => ['Currency', 'CurrencyCode'],
        ],
        'finance.payment_terms' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/PaymentTermsTypes?$select=GroupNumber,PaymentTermsGroupName,NumberOfAdditionalDays&$top=200',
            'key_candidates' => ['GroupNumber'],
            'name_candidates' => ['PaymentTermsGroupName'],
        ],
        'finance.profit_centers' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/ProfitCenters?$top=200',
            'key_candidates' => ['CenterCode', 'Code', 'ProfitCenterCode', 'OcrCode'],
            'name_candidates' => ['CenterName', 'Name', 'ProfitCenterName', 'OcrName'],
        ],
        'finance.distribution_rules' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/DistributionRules?$select=FactorCode,FactorName,InWhichDimension&$top=200',
            'key_candidates' => ['FactorCode', 'OcrCode', 'Code'],
            'name_candidates' => ['FactorName', 'OcrName', 'Name'],
        ],
        'finance.branches' => [
            'module' => 'finance',
            'mode' => 'collection',
            'path' => '/Branches?$select=BPLID,BPLName,Disabled&$top=200',
            'key_candidates' => ['BPLID'],
            'name_candidates' => ['BPLName'],
        ],

        'sales.quotations' => [
            'module' => 'sales',
            'mode' => 'collection',
            'path' => '/Quotations?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'sales.sales_orders' => [
            'module' => 'sales',
            'mode' => 'collection',
            'path' => '/Orders?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'sales.delivery_notes' => [
            'module' => 'sales',
            'mode' => 'collection',
            'path' => '/DeliveryNotes?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'sales.invoices' => [
            'module' => 'sales',
            'mode' => 'collection',
            'path' => '/Invoices?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'sales.credit_notes' => [
            'module' => 'sales',
            'mode' => 'collection',
            'path' => '/CreditNotes?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'sales.returns' => [
            'module' => 'sales',
            'mode' => 'collection',
            'path' => '/Returns?$select=DocEntry,DocNum,CardCode,DocDate,DocTotal,DocStatus&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'sales.incoming_payments' => [
            'module' => 'sales',
            'mode' => 'collection',
            'path' => '/IncomingPayments?$select=DocEntry,DocNum,CardCode,DocDate,TransferSum&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'sales.customers' => [
            'module' => 'sales',
            'mode' => 'collection',
            'path' => '/BusinessPartners?$filter=CardType%20eq%20\'C\'&$select=CardCode,CardName,EmailAddress,Phone1&$top=200',
            'key_candidates' => ['CardCode'],
            'name_candidates' => ['CardName'],
        ],
        'sales.items' => [
            'module' => 'sales',
            'mode' => 'collection',
            'path' => '/Items?$select=ItemCode,ItemName,ItemsGroupCode,UoMGroupEntry&$top=200',
            'key_candidates' => ['ItemCode'],
            'name_candidates' => ['ItemName'],
        ],
        'sales.item_groups' => [
            'module' => 'sales',
            'mode' => 'collection',
            'path' => '/ItemGroups?$select=Number,GroupName&$top=200',
            'key_candidates' => ['Number'],
            'name_candidates' => ['GroupName'],
        ],
        'sales.warehouses' => [
            'module' => 'sales',
            'mode' => 'collection',
            'path' => '/Warehouses?$select=WarehouseCode,WarehouseName,EnableBinLocations&$top=200',
            'key_candidates' => ['WarehouseCode'],
            'name_candidates' => ['WarehouseName'],
        ],

        'inventory.items' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/Items?$select=ItemCode,ItemName,ItemsGroupCode,UoMGroupEntry,InventoryItem,PurchaseItem,SalesItem&$top=200',
            'key_candidates' => ['ItemCode'],
            'name_candidates' => ['ItemName'],
        ],
        'inventory.item_groups' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/ItemGroups?$select=Number,GroupName&$top=200',
            'key_candidates' => ['Number'],
            'name_candidates' => ['GroupName'],
        ],
        'inventory.warehouses' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/Warehouses?$select=WarehouseCode,WarehouseName,EnableBinLocations&$top=200',
            'key_candidates' => ['WarehouseCode'],
            'name_candidates' => ['WarehouseName'],
        ],
        'inventory.bin_locations' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/BinLocations?$select=AbsEntry,BinCode,Warehouse&$top=200',
            'key_candidates' => ['AbsEntry'],
            'name_candidates' => ['BinCode'],
        ],
        'inventory.item_warehouse_info' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/Items?$select=ItemCode,ItemName&$expand=ItemWarehouseInfoCollection&$top=200',
            'key_candidates' => ['ItemCode'],
            'name_candidates' => ['ItemName'],
        ],
        'inventory.inventory_gen_entries' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/InventoryGenEntries?$select=DocEntry,DocNum,DocDate,Comments&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'inventory.inventory_gen_exits' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/InventoryGenExits?$select=DocEntry,DocNum,DocDate,Comments&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'inventory.inventory_transfers' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/StockTransfers?$select=DocEntry,DocNum,DocDate,FromWarehouse,ToWarehouse&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'inventory.inventory_transfer_requests' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/InventoryTransferRequests?$select=DocEntry,DocNum,DocDate,FromWarehouse,ToWarehouse&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'inventory.inventory_counting' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/InventoryCountings?$select=DocumentEntry,DocumentNumber,CountDate,Remarks&$top=200',
            'key_candidates' => ['DocumentEntry', 'DocEntry'],
            'name_candidates' => ['DocumentNumber', 'DocNum'],
        ],
        'inventory.inventory_posting' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/InventoryPostings?$select=DocumentEntry,DocumentNumber,PostingDate,Remarks&$top=200',
            'key_candidates' => ['DocumentEntry', 'DocEntry'],
            'name_candidates' => ['DocumentNumber', 'DocNum'],
        ],
        'inventory.production_orders' => [
            'module' => 'inventory',
            'mode' => 'collection',
            'path' => '/ProductionOrders?$select=AbsoluteEntry,DocumentNumber,ItemNo,DueDate,ProductionOrderStatus&$top=200',
            'key_candidates' => ['AbsoluteEntry', 'DocEntry'],
            'name_candidates' => ['DocumentNumber', 'ItemNo'],
        ],

        'banking.incoming_payments' => [
            'module' => 'banking',
            'mode' => 'collection',
            'path' => '/IncomingPayments?$select=DocEntry,DocNum,CardCode,DocDate,TransferSum&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'banking.vendor_payments' => [
            'module' => 'banking',
            'mode' => 'collection',
            'path' => '/VendorPayments?$select=DocEntry,DocNum,CardCode,DocDate,TransferSum&$top=200',
            'key_candidates' => ['DocEntry'],
            'name_candidates' => ['DocNum'],
        ],
        'banking.deposits' => [
            'module' => 'banking',
            'mode' => 'collection',
            'path' => '/Deposits?$select=DepositNum,DepositType,DepositDate,DepositAccount&$top=200',
            'key_candidates' => ['DepositNum', 'DocEntry'],
            'name_candidates' => ['DepositNum'],
        ],
        'banking.checks_for_payment' => [
            'module' => 'banking',
            'mode' => 'collection',
            'path' => '/ChecksforPayment?$top=200',
            'key_candidates' => ['CheckKey', 'CheckAbsEntry', 'AbsEntry', 'DocEntry'],
            'name_candidates' => ['CheckNumber', 'CheckNum', 'VoucherNum'],
        ],
    ],
];
