<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class IntegrationSetting extends Model
{
    protected $fillable = [
        'sap_service_layer_url',
        'sap_company_db',
        'sap_username',
        'sap_password',
        'sap_ssl_verify',
        'omniful_api_url',
        'omniful_api_key',
        'omniful_api_secret',
        'omniful_webhook_secret',
        'omniful_tenant_code',
        'omniful_seller_code',
        'omniful_access_token',
        'omniful_refresh_token',
        'omniful_token_expires_in',
        'omniful_access_token_expires_at',
        'omniful_seller_api_key',
        'omniful_seller_api_secret',
        'omniful_seller_webhook_secret',
        'omniful_seller_access_token',
        'omniful_seller_refresh_token',
        'omniful_seller_token_expires_in',
        'omniful_seller_access_token_expires_at',
        'sync_direction_items',
        'sync_direction_suppliers',
        'sync_direction_warehouses',
        'sync_direction_inventory',
        'order_fallback_customer_code',
        'order_fallback_customer_code_by_source',
        'order_fallback_warehouse_code',
        'order_payment_enabled',
        'order_payment_transfer_account',
        'order_payment_invoice_type_candidates',
        'order_payment_method_map',
        'order_tax_code_ksa_taxable',
        'order_tax_code_ksa_zero',
        'order_tax_code_foreign',
        'order_freight_expense_code',
    ];

    protected $casts = [
        'sap_password' => 'encrypted',
        'sap_ssl_verify' => 'boolean',
        'omniful_api_key' => 'encrypted',
        'omniful_api_secret' => 'encrypted',
        'omniful_webhook_secret' => 'encrypted',
        'omniful_access_token' => 'encrypted',
        'omniful_refresh_token' => 'encrypted',
        'omniful_token_expires_in' => 'integer',
        'omniful_access_token_expires_at' => 'datetime',
        'omniful_seller_api_key' => 'encrypted',
        'omniful_seller_api_secret' => 'encrypted',
        'omniful_seller_webhook_secret' => 'encrypted',
        'omniful_seller_access_token' => 'encrypted',
        'omniful_seller_refresh_token' => 'encrypted',
        'omniful_seller_token_expires_in' => 'integer',
        'omniful_seller_access_token_expires_at' => 'datetime',
        'sync_direction_items' => 'string',
        'sync_direction_suppliers' => 'string',
        'sync_direction_warehouses' => 'string',
        'sync_direction_inventory' => 'string',
        'order_fallback_customer_code' => 'string',
        'order_fallback_customer_code_by_source' => 'string',
        'order_fallback_warehouse_code' => 'string',
        'order_payment_enabled' => 'boolean',
        'order_payment_transfer_account' => 'string',
        'order_payment_invoice_type_candidates' => 'array',
        'order_payment_method_map' => 'string',
        'order_tax_code_ksa_taxable' => 'string',
        'order_tax_code_ksa_zero' => 'string',
        'order_tax_code_foreign' => 'string',
        'order_freight_expense_code' => 'string',
    ];
}
